### ISSUE TITLE
Unable to find static field: main in class io.papermc.paperclip.Paperclip

### ISSUE THREAD

**Issue by caiorulli** [lambdaisland/witchcraft-plugin#2]
Hi! I've been trying to run witchcraft in PaperMC and I have been getting the following error. (Will attach the full log)
PaperMC version: 1.17.1-399
Witchcraft plugin version: 0.5.27 for paper 1.17
Java version: openjdk version "17.0.1" 2021-10-19

Is there anything I might be doing wrong to cause this?
(Obs.: if this should go to the main witchcraft repo instead, please let me know)
Thanks in advance!

```
[19:56:05] [Server thread/INFO]: [Witchcraft] require: lambdaisland.witchcraft
[19:56:07] [Server thread/INFO]: [Witchcraft] require: lambdaisland.witchcraft.paper
[19:56:07] [Server thread/ERROR]: [Witchcraft] Require namespace failed: lambdaisland.witchcraft.paper
[19:56:07] [Server thread/ERROR]: [Witchcraft] clojure.lang.Compiler$CompilerException : Syntax error compiling at (lambdaisland/witchcraft/paper.clj:51:11).
[19:56:07] [Server thread/WARN]: Syntax error compiling at (lambdaisland/witchcraft/paper.clj:51:11).
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6812)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6122)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7099)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6124)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$TryExpr$Parser.parse(Compiler.java:2318)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6124)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$FnMethod.parse(Compiler.java:5471)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$FnExpr.parse(Compiler.java:4033)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7109)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3892)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7113)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7099)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6124)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2841)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6124)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$FnMethod.parse(Compiler.java:5471)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$FnExpr.parse(Compiler.java:4033)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7109)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7099)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.access$300(Compiler.java:38)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:596)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSeq(Compiler.java:7111)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6793)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6749)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.eval(Compiler.java:7185)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.load(Compiler.java:7640)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RT.loadResourceScript(RT.java:381)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RT.loadResourceScript(RT.java:372)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RT.load(RT.java:459)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RT.load(RT.java:424)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load$fn__6856.invoke(core.clj:6115)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load.invokeStatic(core.clj:6114)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load.doInvoke(core.clj:6098)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RestFn.invoke(RestFn.java:408)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load_one.invokeStatic(core.clj:5897)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load_one.invoke(core.clj:5892)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load_lib.invokeStatic(core.clj:5936)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load_lib.doInvoke(core.clj:5917)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RestFn.applyTo(RestFn.java:142)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$apply.invokeStatic(core.clj:669)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load_libs.invokeStatic(core.clj:5974)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$load_libs.doInvoke(core.clj:5958)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RestFn.applyTo(RestFn.java:137)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$apply.invokeStatic(core.clj:669)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$require.invokeStatic(core.clj:5996)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.core$require.doInvoke(core.clj:5996)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.RestFn.invoke(RestFn.java:408)
[19:56:07] [Server thread/WARN]: 	at lambdaisland.witchcraft.plugin$on_enable$fn__7120.invoke(plugin.clj:55)
[19:56:07] [Server thread/WARN]: 	at lambdaisland.witchcraft.plugin$on_enable.invokeStatic(plugin.clj:54)
[19:56:07] [Server thread/WARN]: 	at lambdaisland.witchcraft.plugin$on_enable.invoke(plugin.clj:34)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Var.invoke(Var.java:384)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//com.lambdaisland.witchcraft.ClojurePlugin.onEnable(ClojurePlugin.java:20)
[19:56:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:56:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:56:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:56:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[19:56:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[19:56:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[19:56:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[19:56:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[19:56:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:56:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:56:07] [Server thread/WARN]: Caused by: java.lang.RuntimeException: Unable to find static field: main in class io.papermc.paperclip.Paperclip
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Util.runtimeException(Util.java:221)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyzeSymbol(Compiler.java:7315)
[19:56:07] [Server thread/WARN]: 	at witchcraft-plugin-0.5.27-for-paper-1.17-shaded.jar//clojure.lang.Compiler.analyze(Compiler.java:6772)
[19:56:07] [Server thread/WARN]: 	... 83 more

```

[latest.log](https://github.com/lambdaisland/witchcraft-plugin/files/7697858/latest.log)

**Comment by plexus** [comment]
Darn, the 1.18 compatibility might have broken 1.17. I'll try to have a look.

**Comment by plexus** [comment]
This should be fixed in

```
[com.lambdaisland/witchcraft "0.8.205"]
{com.lambdaisland/witchcraft {:mvn/version "0.8.205"}}
```

**Comment by caiorulli** [comment]
Cool! Thanks! Will try it!
